services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: coffee-backend
    ports:
      - "8000:8000"
    volumes:
      - ./data.xlsx:/app/data.xlsx   # Mount example Excel file into container
    environment:
      - EXCEL_FILE=/app/data.xlsx    # Override path inside container if needed

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: coffee-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:8000
