services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: coffee-backend
    volumes:
      - ./data.xlsx:/app/data.xlsx   # Mount example Excel file into container
    environment:
      - EXCEL_FILE=/app/data.xlsx    # Override path inside container if needed

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: coffee-frontend
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: coffee-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend